#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <windows.h>


void limpiarPantalla() { system("cls"); }

void muertePor_tristeza(){
    while(true){
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ██ ██ ██   \n");
        printf(" █  ████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█ ▀▄▀  ▀▄▀ █ \n");
        printf("█ ▀ ▀  ▀ ▀ █ \n");
        printf("█    ▄▄    █ \n");
        printf(" █  ▀  ▀  █  \n");
        printf("  ████████   \n");
        printf(" █ █    █ █  \n");
        printf(" ██      ██  \n");
        printf("  ████████   \n");
        printf("   ██  ██    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄████ ▄██   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█  ▀▄▀  ▀▄▀█ \n");
        printf("█  ▀ ▀  ▀ ▀█ \n");
        printf("█     ▄▄   █ \n");
        printf(" █   ▀  ▀ █  \n");
        printf("  ████████   \n");
        printf("  █ █    ██  \n");
        printf("  ██     █  \n");
        printf("  ████████   \n");
        printf("    ██ ██    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄▄███ ▄▄█   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█   ▀▄▀  ▀▄█ \n");
        printf("█   ▀ ▀  ▀ █ \n");
        printf("█      ▄▄  █ \n");
        printf(" █    ▀  ▀█  \n");
        printf("  ████████   \n");
        printf("  █  █   █  \n");
        printf("  ███    █  \n");
        printf("  ████████   \n");
        printf("     ████    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄▄███ ▄▄█   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█    ▀▄▀  ▀█ \n");
        printf("█    ▀ ▀  ▀█ \n");
        printf("█      ▄▄  █ \n");
        printf(" █    ▀  ▀█  \n");
        printf("  ████████   \n");
        printf("  █ █ █  █  \n");
        printf("  █ ██   █  \n");
        printf("  ████████   \n");
        printf("      ███    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄▄███ ▄▄█   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█     ▀▄▀  █ \n");
        printf("█     ▀ ▀  █ \n");
        printf("█       ▄▄ █ \n");
        printf(" █     ▀  █  \n");
        printf("  ████████   \n");
        printf("  █  █ █ █  \n");
        printf("  █  ██  █  \n");
        printf("  ████████   \n");
        printf("       ██    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄▄███ ▄▄█   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█     ▀▄▀  █ \n");
        printf("█     ▀ ▀  █ \n");
        printf("█       ▄▄ █ \n");
        printf(" █     ▀  █  \n");
        printf("  ████████   \n");
        printf("  █   █ ██   \n");
        printf("  █   ██ █   \n");
        printf("  ████████   \n");
        printf("       ██    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄▄███ ▄▄█   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█      ▀▄▀ █ \n");
        printf("█      ▀ ▀ █ \n");
        printf("█        ▄▄█ \n");
        printf(" █      ▀ █  \n");
        printf("  ████████   \n");
        printf("  █    █ █ \n");
        printf("  █    ███   \n");
        printf("  ████████   \n");
        printf("       ██    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄▄███ ▄▄█   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█       ▀▄▀█ \n");
        printf("█       ▀ ▀█ \n");
        printf("█         ▄█ \n");
        printf(" █       ▀█  \n");
        printf("  ████████   \n");
        printf("  █     █ █  \n");
        printf("  █     ███  \n");
        printf("  ████████   \n");
        printf("      ███    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄▄███ ▄▄█   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█        ▀▄█ \n");
        printf("█        ▀ █ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf("  █      ██  \n");
        printf("  █      ██  \n");
        printf("  ████████   \n");
        printf("      ███    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄████ ▄██   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█         ▀█ \n");
        printf("█         ▀█ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf("  █      █  \n");
        printf("  █      █  \n");
        printf("  ████████   \n");
        printf("      ███    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄█▄██ ▄█▄   \n");
        printf(" █  █████ █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf("  █      █  \n");
        printf("  █      █  \n");
        printf("  ████████   \n");
        printf("     ████    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ▄█ ██ ██▄   \n");
        printf(" █  ████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf("  █      █  \n");
        printf("  █      █  \n");
        printf("  ████████   \n");
        printf("    ██ ██    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf("  ██ ██ ██   \n");
        printf(" █  ████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf("  █      █  \n");
        printf("  █      █  \n");
        printf("  ████████   \n");
        printf("   ██  ██    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" ▄██ ██ █▄   \n");
        printf(" █  ████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf("  █      █  \n");
        printf("  █      █  \n");
        printf("  ████████   \n");
        printf("   ██ ██    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" ▄█▄ ██▄█▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf("  █      █  \n");
        printf("  █      █  \n");
        printf("  ████████   \n");
        printf("   ████    \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" ██▄ ████▄    \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█▀         █ \n");
        printf("█▀         █ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf("  █      █  \n");
        printf("  █      █  \n");
        printf("  ████████   \n");
        printf("   ███       \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" █▄▄ ███▄▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█▀▄        █ \n");
        printf("█▀         █ \n");
        printf("█          █ \n");
        printf(" █        █  \n");
        printf("  ████████   \n");
        printf(" ██      █  \n");
        printf(" ██      █  \n");
        printf("  ████████   \n");
        printf("   ███        \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" █▄▄ ███▄▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█▀▄▀       █ \n");
        printf("█▀ ▀       █ \n");
        printf("█▄         █ \n");
        printf(" █▀       █  \n");
        printf("  ████████   \n");
        printf(" █ █     █  \n");
        printf(" ███     █  \n");
        printf("  ████████   \n");
        printf("   ███        \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" █▄▄ ███▄▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█ ▀▄▀      █ \n");
        printf("█ ▀ ▀      █ \n");
        printf("█▄▄        █ \n");
        printf(" █ ▀      █  \n");
        printf("  ████████   \n");
        printf("  █ █    █  \n");
        printf("  ███    █  \n");
        printf("  ████████   \n");
        printf("   ██        \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" █▄▄ ███▄▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█  ▀▄▀     █ \n");
        printf("█  ▀ ▀     █ \n");
        printf("█ ▄▄       █ \n");
        printf(" █  ▀     █  \n");
        printf("  ████████   \n");
        printf("  ██ █   █  \n");
        printf("  █ ██   █  \n");
        printf("  ████████   \n");
        printf("   ██        \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" █▄▄ ███▄▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█  ▀▄▀     █ \n");
        printf("█  ▀ ▀     █ \n");
        printf("█ ▄▄       █ \n");
        printf(" █  ▀     █  \n");
        printf("  ████████   \n");
        printf("  █ █ █  █  \n");
        printf("  █  ██  █  \n");
        printf("  ████████   \n");
        printf("   ██        \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" █▄▄ ███▄▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█▀  ▀▄▀    █ \n");
        printf("█▀  ▀ ▀    █ \n");
        printf("█  ▄▄      █ \n");
        printf(" █▀  ▀    █  \n");
        printf("  ████████   \n");
        printf("  █  █ █ █  \n");
        printf("  █   ██ █  \n");
        printf("  ████████   \n");
        printf("   ███        \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" █▄▄ ███▄▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█▄▀  ▀▄▀   █ \n");
        printf("█ ▀  ▀ ▀   █ \n");
        printf("█  ▄▄      █ \n");
        printf(" █▀  ▀    █  \n");
        printf("  ████████   \n");
        printf("  █   █  █  \n");
        printf("  █    ███  \n");
        printf("  ████████   \n");
        printf("   ████       \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
        printf("     ██      \n");
        printf("     ██      \n");
        printf(" ██▄ ████▄   \n");
        printf(" █ █████  █  \n");
        printf(" █        █  \n");
        printf("█          █ \n");
        printf("█▀▄▀  ▀▄▀  █ \n");
        printf("█▀ ▀  ▀ ▀  █ \n");
        printf("█   ▄▄     █ \n");
        printf(" █ ▀  ▀   █  \n");
        printf("  ████████   \n");
        printf(" ██    █ █  \n");
        printf("  █     ██  \n");
        printf("  ████████   \n");
        printf("   ██ ██      \n");
        printf("             \n");
        printf("             \n");
        printf("             \n");
        printf("▄▄▄▄▄▄▄▄▄▄▄▄ \n");
        Sleep(250);
        limpiarPantalla();
    }
}
  

void muertePor_agotamiento(){
    while(true){
        printf("                   \n");
    printf("                   \n"),
    printf("      ▄              \n");
    printf("    ▄▀ ▀▄    ▄       \n");
    printf("  ▄▀     ▀▄▄▀ ▀▄     \n");
    printf(" █     ▄▄▄▄     █    \n");
    printf("█   ▄▀▀████▀▀▄   ▀▄  \n");
    printf("▀▄  █▄▄████▄▄█    █  \n");
    printf(" █   ██▀██▀██    ▄▀  \n");
    printf("  ▀▄   ▄▄▄▄    ▄▀    \n");
    printf("     ▄▄▄▄▄▄▄▄        \n");
    printf("    █ █    █ █       \n");
    printf("    ██      ██       \n");
    printf("     ████████        \n");
    printf("      ██  ██         \n");
    Sleep(250);
    limpiarPantalla();
    printf("                   \n");
    printf("                   \n"),
    printf("     ▀▄              \n");
    printf("    ▄▀ ▀▄    ▄       \n");
    printf("  ▄▀     ▀▄▄▀ ▀▄     \n");
    printf(" █     ▄▄▄▄     █    \n");
    printf("█   ▄▀▀████▀▀▄   ▄  \n");
    printf("▀▄  █▄▄████▄▄█   █  \n");
    printf(" █   ██▀██▀██    ▀  \n");
    printf("  ▀▄   ▄▄▄▄    ▄▀    \n");
    printf("     ▄▄▄▄▄▄▄▄        \n");
    printf("    █ █    █ █       \n");
    printf("    ██      ██       \n");
    printf("     ████████        \n");
    printf("      ██  ██         \n");
    Sleep(250);
    limpiarPantalla();
    printf("                   \n");
    printf("     ▄              \n"),
    printf("      ▄              \n");
    printf("     █ ▀▄    ▄▀       \n");
    printf("  ▄ ▀    ▀▄▄▀ ▀▄     \n");
    printf(" █     ▄▄▄▄     █    \n");
    printf("█   ▄▀▀████▀▀▄   ▄  \n");
    printf("▀▄  █▄▄████▄▄█    █  \n");
    printf(" █   ██▀██▀██    ▀  \n");
    printf("  ▀▄   ▄▄▄▄    ▄▀    \n");
    printf("     ▄▄▄▄▄▄▄▄        \n");
    printf("    █ █    █ █       \n");
    printf("    ██      ██       \n");
    printf("     ████████        \n");
    printf("      ██  ██         \n");
    Sleep(250);
    limpiarPantalla();
    printf("                   \n");
    printf("     ▀              \n"),
    printf("      ▄▀      ▄        \n");
    printf("     █ ▀▄    ▄       \n");
    printf("   ▀     ▀▄▄▀ ▀▄     \n");
    printf("  █    ▄▄▄▄     █    \n");
    printf(" █  ▄▀▀████▀▀▄   ▀▄  \n");
    printf(" ▄  █▄▄████▄▄█    █  \n");
    printf(" █   ██▀██▀██    ▀  \n");
    printf("  ▀▄   ▄▄▄▄    ▄▀    \n");
    printf("     ▄▄▄▄▄▄▄▄        \n");
    printf("    █ █    █ █       \n");
    printf("    ██      ██       \n");
    printf("     ████████        \n");
    printf("      ██  ██         \n");
    Sleep(250);
    limpiarPantalla();
    printf("    ▄               \n");
    printf("       ▄      ▄      \n"),
    printf("      ▄              \n");
    printf("    ▄▀ ▀▄    ▄       \n");
    printf("   ▀     ▀▄▄▀ █     \n");
    printf("  █    ▄▄▄▄     █    \n");
    printf("█   ▄▀▀████▀▀▄   ▀▄  \n");
    printf("▄   █▄▄████▄▄█    █  \n");
    printf(" █   ██▀██▀██    ▀  \n");
    printf("  ▀▄   ▄▄▄▄    ▄▀    \n");
    printf("     ▄▄▄▄▄▄▄▄        \n");
    printf("    █ █    █ █       \n");
    printf("    ██      ██       \n");
    printf("     ████████        \n");
    printf("      ██  ██         \n");
    Sleep(250);
    limpiarPantalla();
    printf("    ▀        ▄       \n");
    printf("       ▀            \n"),
    printf("      ▄              \n");
    printf("    ▄▀ ▀▄    █      \n");
    printf("   ▀     ▀▄▄▀ ▀      \n");
    printf("  █    ▄▄▄▄    ▀▄    \n");
    printf("█   ▄▀▀████▀▀▄   ▀  \n");
    printf("▀▄  █▄▄████▄▄█   █  \n");
    printf(" █   ██▀██▀██    ▀  \n");
    printf("  ▀▄   ▄▄▄▄    ▄    \n");
    printf("     ▄▄▄▄▄▄▄▄        \n");
    printf("    █ █    █ █       \n");
    printf("    ██      ██       \n");
    printf("     ████████        \n");
    printf("      ██  ██         \n");
    Sleep(250);
    limpiarPantalla();
    printf("       ▀             \n");
    printf("                   \n"),
    printf("      ▄              \n");
    printf("    ▄▀ ▀▄    ▄▄       \n");
    printf("   ▄     ▀▄▄▀  █     \n");
    printf("  █    ▄▄▄▄     ▄    \n");
    printf("█   ▄▀▀████▀▀▄   ▀  \n");
    printf("▀▄  █▄▄████▄▄█    █  \n");
    printf(" █   ██▀██▀██    ▄ \n");
    printf("  ▀▄   ▄▄▄▄    ▄▀    \n");
    printf("     ▄▄▄▄▄▄▄▄        \n");
    printf("    █ █    █ █       \n");
    printf("    ██      ██       \n");
    printf("     ████████        \n");
    printf("      ██  ██         \n");
    Sleep(250);
    limpiarPantalla();
    printf("                   \n");
    printf("                   \n");
    printf("      ▄              \n");
    printf("    ▄▀ ▀▄    ▄       \n");
    printf("   ▀     ▀▄▄▀ ▀█     \n");
    printf(" █     ▄▄▄▄         \n");
    printf("█   ▄▀▀████▀▀▄   ▀▄  \n");
    printf("▀▄  █▄▄████▄▄█    █  \n");
    printf(" █   ██▀██▀██    ▄▀  \n");
    printf("  ▀▄   ▄▄▄▄    ▄▀    \n");
    printf("     ▄▄▄▄▄▄▄▄        \n");
    printf("    █ █    █ █       \n");
    printf("    ██      ██       \n");
    printf("     ████████        \n");
    printf("      ██  ██         \n");
    Sleep(250);
    limpiarPantalla();
    }
    
}

void muertePor_hambre(){
    while(true){
        printf("              \n");
        printf("              \n");
        printf("   ██   ██    \n");
        printf("  █  ███  █   \n");
        printf("  █       █   \n");
        printf(" █         █  \n");
        printf("█ ▀▄▀   ▀▄▀ █ \n");
        printf("█ ▀ ▀   ▀ ▀ █ \n");
        printf(" █  ▄▀▀▀▄  █  \n");
        printf("  █ ▀▄▄▄▀ █   \n");
        printf("   ███████    \n");
        printf("  █   █   █   \n");
        printf("  █   █   █   \n");
        printf("     ███      \n");
        printf("    █   █     \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("   ██   ██    \n");
        printf("  █  ███  █   \n");
        printf("  █       █   \n");
        printf(" █         █  \n");
        printf("█ ▀▄▀   ▀▄▀ █ \n");
        printf("█ ▀ ▀   ▀ ▀ █ \n");
        printf(" █  ▄▀▀▀▄  █  \n");
        printf("  █ ▀▄▄▄▀ █   \n");
        printf("   ███████    \n");
        printf("  █   █   █   \n");
        printf("  █       █   \n");
        printf("     ███      \n");
        printf("    █   █     \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("   ██   ██    \n");
        printf("  █  ███  █   \n");
        printf("  █       █   \n");
        printf(" █         █  \n");
        printf("█ ▀▄▀   ▀▄▀ █ \n");
        printf("█ ▀ ▀   ▀ ▀ █ \n");
        printf(" █  ▄▀▀▀▄  █  \n");
        printf("  █ ▀▄▄▄▀ █   \n");
        printf("   ███████    \n");
        printf("  █       █   \n");
        printf("  █       █   \n");
        printf("     █ █     \n");
        printf("    █   █     \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("   ██   ██    \n");
        printf("  █  ███  █   \n");
        printf("  █       █   \n");
        printf(" █         █  \n");
        printf("█ ▀▄▀   ▀▄▀ █ \n");
        printf("█ ▀ ▀   ▀ ▀ █ \n");
        printf(" █  ▄▀▀▀▄  █  \n");
        printf("   █▀▄▄▄▀█   \n");
        printf("    █████    \n");
        printf("  █       █   \n");
        printf("  █       █   \n");
        printf("             \n");
        printf("    █   █     \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("   ██   ██    \n");
        printf("   █ ███ █   \n");
        printf("  █       █   \n");
        printf(" █         █  \n");
        printf("█ ▀▄▀   ▀▄▀ █ \n");
        printf(" █▀ ▀   ▀ ▀█ \n");
        printf("  █ ▄▀▀▀▄ █  \n");
        printf("   █▀▄▄▄▀█   \n");
        printf("    █████    \n");
        printf("  █       █   \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("    █   █  \n");
        printf("   █ ███ █   \n");
        printf("  █       █  \n");
        printf(" █▀▄▀   ▀▄▀█ \n");
        printf(" █▀ ▀   ▀ ▀█ \n");
        printf("  █ ▄▀▀▀▄ █  \n");
        printf("   █▀▄▄▄▀█   \n");
        printf("    █████    \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("    █   █  \n");
        printf("   █ ███ █   \n");
        printf("  █       █  \n");
        printf(" █▀▄▀   ▀▄▀█ \n");
        printf("  █ ▀   ▀ █ \n");
        printf("   █▄▀▀▀▄█  \n");
        printf("    █▄▄▄█   \n");
        printf("     ▀▀▀   \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("    █ █ █    \n");
        printf("   █     █  \n");
        printf("  █▄▀   ▀▄█ \n");
        printf("  █ ▀   ▀ █ \n");
        printf("   █▄▀▀▀▄█  \n");
        printf("    █▄▄▄█   \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("     █ █    \n");
        printf("    █   █  \n");
        printf("   █▀   ▀█ \n");
        printf("   █▀   ▀█ \n");
        printf("    █▀▀▀█  \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("         \n");
        printf("     █ █     \n");
        printf("   █▀   ▀█ \n");
        printf("   █▀   ▀█ \n");
        printf("     ▀▀▀  \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("         \n");
        printf("           \n");
        printf("    █▀  ▀█ \n");
        printf("    █▀  ▀█ \n");
        printf("         \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("         \n");
        printf("           \n");
        printf("     █▀▀█ \n");
        printf("      ▀▀ \n");
        printf("         \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("         \n");
        printf("           \n");
        printf("      ▄▄ \n");
        printf("      ▀▀ \n");
        printf("         \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("         \n");
        printf("           \n");
        printf("      ▄▄ \n");
        printf("      ▀▀ \n");
        printf("         \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("         \n");
        printf("           \n");
        printf("      ▄▄ \n");
        printf("      ▀▀ \n");
        printf("         \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("         \n");
        printf("           \n");
        printf("             \n");
        printf("      <pop> \n");
        printf("         \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();
        printf("              \n");
        printf("              \n");
        printf("       \n");
        printf("       \n");
        printf("         \n");
        printf("           \n");
        printf("             \n");
        printf("       \n");
        printf("         \n");
        printf("         \n");
        printf("         \n");
        printf("           \n");
        printf("           \n");
        printf("             \n");
        printf("            \n");
        Sleep(250);
        limpiarPantalla();

    }
  
return;
}


int main(){
    system("chcp 65001");
        limpiarPantalla();

    muertePor_tristeza();
    //muertePor_agotamiento();    
    //muertePor_hambre();
    return 0;
}